name: Check Util Hashes

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      # Generate hashes
      - name: Generate hashes
        shell: cmd
        run: |
          for /f "delims=" %%a in ('cd') do set "CurrentDir=%%a"
          cd src\DuckOS_Modules
          echo "# Util Hashes" > %currentdir%\utilhashes.md
          for %%i in (*.exe) do (
              echo " " >>%currentdir%\utilhashes.md
              echo "- **%%i**" >>%currentdir%\utilhashes.md
              echo "  - Hash in **SHA256**: \`certutil -hashfile "%%i" SHA256\`" >>%currentdir%\utilhashes.md
              echo "  - Size: \`%%~zi bytes\`" >>%currentdir%\utilhashes.md
      
      # Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - check util hashes"
          git add utilhashes.md
          git commit -m "Check util hashes"
          git push
