name: CheckHashes
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a set of commands using powershell
      - name: Get hashes
        shell: cmd
        run: |
          set "CurrentDir=%~dp0"
          for %%i in (src\DuckOS_Modules\*.exe) do (
              echo:## "%%i" >%currentdir%\utilhashes.md
              echo:Hash of "%%i" in **SHA256**: >>%currentdir%\utilhashes.md
              certutil -hashfile "%%i" SHA256 >>%currentdir%\utilhashes.md
              FOR %%A IN ("%%i") DO set size=%%~zA
              echo:Size of "*%%i*": %size% >>%currentdir%\utilhashes.md


      - name: Commit changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - check util hashes"
          git add utilhashes.md
          git commit -m "Check util hashes"
          git push
