# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.

name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '44 11 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue detected. Closing..'
        stale-pr-message: 'Stale pull request detected. Closing..'
        stale-issue-label: 'stale issue'
        stale-pr-label: 'pr: stale'
