name: Update

# Controls when the workflow will run
on:
    push:
        branches: [ main ]
    schedule:
        - cron: '*/30 */12 */5 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Download libraries
        run: | 
            curl -L -f https://dl5.oo-software.com/files/ooshutup10/OOSU10.exe > src/DuckOS_Modules/OOSU10.exe
            curl -L -f https://sourceforge.net/projects/sevenzip/files/latest/download > src/DuckOS_Modules/Utils/7zip.exe
            curl -L -f https://sourceforge.net/projects/open-shell.mirror/files/latest/download > src/DuckOS_Modules/Utils/OpenShell.exe
      # Runs a set of commands using the runners shell
      - name: Commit changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update modules"
          git add --all
          git commit -m "Update modules"
          git push
